name: base-environment
channels:
  - conda-forge
  - bioconda
dependencies:
  - condax
  - r-base=4.0  # temporary https://github.com/jupyterhub/repo2docker/pull/1141
  - r-tidyverse
  - rpy2
  - jupyterlab-lsp
  - python-lsp-server
  - r-languageserver
  - biopython
  - pysam
