name: base-environment
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.9
  - nodejs=16
  - retrolab
  - pandas
  - numpy
  - dask
  - scikit-learn
  - scikit-image
  - matplotlib
  - bokeh
  - plotly
  # "SemVer" error issue: https://github.com/jupyterhub/repo2docker/issues/1140
  # Keep the version until repo2docker is upgraded from 2022.02.0.
  - r-base=4.0
  - r-tidyverse
  - rpy2
  - jupyterlab-lsp
  - python-lsp-server
  - r-languageserver
  - biopython
  - pysam
  - pipx
  # Keep this until repo2docker's default micromamba is bumped.
  - micromamba>=0.25
  - mamba
  - pip
  - pip:
    - nbgitpuller
