name: base-environment
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.9
  - nodejs=16
  - retrolab
  - pandas
  - numpy
  - dask
  - scikit-learn
  - scikit-image
  - matplotlib
  - bokeh
  - plotly
  - pipx
  - condax
  - r-base=4.0  # temporary https://github.com/jupyterhub/repo2docker/pull/1141
  - r-tidyverse
  - rpy2
  - jupyterlab-lsp
  - python-lsp-server
  - r-languageserver
  - biopython
  - pysam
  - pip
  - pip:
    - nbgitpuller