#!/bin/bash

# https://repo2docker.readthedocs.io/en/latest/config_files.html#postbuild-run-code-after-installing-the-environment
# > Note that by default the build will not be stopped
# > if an error occurs inside a shell script. You should
# > include set -e or the equivalent at the start of the
# >  script to avoid errors being silently ignored.
set -ex

# install triton-lsp
npm install yamaton/triton-lsp
ln -s ./node_modules/triton-lsp/scripts/jupyter_server_config.py .

# install programs in each conda environment
TOOLS=( "$(cat ./_tools.txt)" )
for _tool in ${TOOLS[*]}; do
    echo "Installing ${_tool}"
    # retry if nonzero exit status occurs
    if [[ ! ($(condax install -c conda-forge -c bioconda "$_tool")) ]]; then
        condax remove "$_tool"
        condax install -c conda-forge -c bioconda "$_tool"
    fi
done

conda clean --all --yes --force-pkgs-dirs

## Fix 404 Error with nbgitpuller link
## https://jupyterhub.github.io/nbgitpuller/install.html#nbgitpuller-link-shows-404-not-found
jupyter serverextension enable nbgitpuller --sys-prefix
