#!/bin/bash

# jupyterlab-lsp fails to find bash-language-server if installed with '-g'.
# Related? https://github.com/jupyter-lsp/jupyterlab-lsp/issues/181

# install patched bash-language-server
npm install https://github.com/yamaton/bash-language-server/releases/download/server-2.0.0/bash-language-server-2.0.0.tgz

TOOLS=( "$(cat ./_tools.txt)" )
for _tool in ${TOOLS[*]}; do
    echo "Installing ${_tool}"
    # retry if nonzero exit status occurs
    if [[ ! ($(condax install -c conda-forge -c bioconda "$_tool")) ]]; then
        condax remove "$_tool"
        condax install -c conda-forge -c bioconda "$_tool"
    fi
done

conda clean --all --yes --force-pkgs-dirs

## Fix 404 Error with nbgitpuller link
## https://jupyterhub.github.io/nbgitpuller/install.html#nbgitpuller-link-shows-404-not-found
jupyter serverextension enable nbgitpuller --sys-prefix
