name: base-environment
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.9
  - nodejs=16
  - retrolab
  - pandas
  - numpy
  - dask
  - scikit-learn
  - scikit-image
  - matplotlib
  - bokeh
  - plotly
  - r-base
  - r-tidyverse
  - r-markdown
  - r-httr
  - r-shinydashboard
  - r-biocmanager
  - r-leaflet
  - rpy2
  - jupyterlab-lsp
  - python-lsp-server
  - r-languageserver
  - biopython
  - pysam
  - pipx
  - mamba
  - pip
  - pip:
    - nbgitpuller
