name: base-environment
channels:
  - conda-forge
  - bioconda
  - nodefaults

dependencies:
  - python=3.9
  - nodejs=16
  - retrolab
  - pandas
  - numpy
  - dask
  - scikit-learn
  - scikit-image
  - matplotlib
  - bokeh
  - plotly
  - r-base
  - r-tidyverse
  - r-markdown
  - r-httr
  - r-shinydashboard
  - r-biocmanager
  - r-leaflet
  - r-gplots
  - rpy2
  - bioconductor-tximport
  - bioconductor-biomart
  - bioconductor-edger
  - bioconductor-deseq2
  - jupyterlab >=3.3.0,<4.0.0a0
  - jupyter_server >=1.1.2
  - retrolab >=0.3.0,<0.4
  - nbgitpuller
  - jupyterlab-link-share
  - flake8 >=3.5
  - pylint
  - pylsp-mypy
  - python-lsp-server
  - ruamel_yaml
  - r-languageserver
  - bash_kernel
  - biopython
  - pysam
  - pipx
  - pip
  - mamba
  - micromamba
  - pip:
    - igv-notebook


