name: base-environment
channels:
  - conda-forge
  - bioconda
  - nodefaults

dependencies:
  - python=3.10
  - nodejs >=16,!=17,<19  # jupyterlab-lsp
  - pandas
  - numpy
  - dask
  - polars
  - scikit-learn
  - scikit-image
  - matplotlib
  - bokeh
  - plotly
  - r-base >=4.2
  - r-tidyverse
  - r-markdown
  - r-httr
  - r-shinydashboard
  - r-biocmanager
  - r-gplots
  - r-sleuth
  - r-ggpubr
  - r-hrbrthemes
  - r-ggthemes
  - rpy2
  - bioconductor-tximport
  - bioconductor-biomart
  - bioconductor-edger
  - bioconductor-deseq2
  ## >>> --- ensure jupyter server ----
  - jupyterlab >=3.6.0,<4.0.0a0  # jupyterlab-lsp
  # [NOTE] jupyterhub 1.5.0 and jupyterhub-singleuser 4.0.0 fails to auth
  - jupyter_server >=2,<3
  - jupyterhub-singleuser >=3.1.0,<4
  ## <<< ------------------------------
  - websockify  # jupyter-remote-desktop-proxy needs this
  - nbgitpuller
  - jupyter-archive
  - jlab-enhanced-launcher
  - jupyterlab-link-share
  - jupyterlab-copy-relative-path
  - flake8 >=3.5
  - pylint
  - pylsp-mypy
  - python-lsp-server
  - ruamel_yaml
  - r-languageserver
  - biopython
  - pysam
  - pipx
  - pip
  - jupyterlab-spreadsheet-editor
  - theme-darcula
  - jupyterlab-night
  - jupyterlab_miami_nights
  - pip:
    - git+https://github.com/jpmorganchase/jupyter-fs
    - git+https://github.com/triton-lab/myextension@main
    - git+https://github.com/yamaton/jupyterlab-qzv@dev
    - git+https://github.com/yamaton/bash_kernel@dev
    - git+https://github.com/yamaton/jupyter-remote-desktop-proxy@test
    - git+https://github.com/yamaton/jupyterlab_legos_ui
    - git+https://github.com/yamaton/jupyterlab_darkside_ui
