name: base-environment
channels:
  - conda-forge
  - bioconda
  - nodefaults

dependencies:
  - python=3.10
  - nodejs=16  # jupyterlab-lsp
  - pandas
  - numpy
  - dask
  - polars
  - scikit-learn
  - scikit-image
  - matplotlib
  - bokeh
  - plotly
  - r-base >=4.2
  - r-tidyverse
  - r-dplyr
  - r-tidyr
  - r-markdown
  - r-httr
  - r-shinydashboard
  - r-biocmanager
  - r-leaflet
  - r-gplots
  - r-ggplot2
  - r-sleuth
  - r-ggpubr
  - r-hrbrthemes
  - r-ggthemes
  - rpy2
  - bioconductor-tximport
  - bioconductor-biomart
  - bioconductor-edger
  - bioconductor-deseq2
  ## >>> --- ensure jupyter server ----
  - jupyterlab >=3.3.0,<4.0.0a0
  - jupyter_server <2.0.0
  - jupyterhub-singleuser >=3.1.0
  ## <<< ------------------------------
  - retrolab >=0.3.0,<0.4
  - nbgitpuller
  - jupyter-archive
  - jupyterlab-link-share
  - jupyterlab-copy-relative-path
  - flake8 >=3.5
  - pylint
  - pylsp-mypy
  - python-lsp-server
  - ruamel_yaml
  - r-languageserver
  - bash_kernel
  - biopython
  - pysam
  - pipx
  - pip
  - theme-darcula
  - pip:
    - igv-notebook
    - jupyterlab-spreadsheet-editor
    - jupyter-fs
    - jupyter_scheduler
    # - jupyterlab_legos_ui
    # - jupyterlab_darkside_ui
