#!/bin/bash


# Set $SHELL if zsh is available
zshloc="$(command -v zsh)"
if [[ -n "$zshloc" ]]; then
    export SHELL="$zshloc"
fi


# Default timezone is non-standard '/UTC',
# which triggers an error in `tzlocal` with python<=3.8
export TZ=Etc/UTC


# A hack to force running Jupyter Server backend
if [[ -n $JUPYTERHUB_CLIENT_ID ]]; then
    # === For JupyterHub build ===
    # https://jupyterhub.readthedocs.io/en/stable/reference/config-user-env.html#switching-back-to-the-classic-notebook
    export JUPYTERHUB_SINGLEUSER_APP='jupyter_server.serverapp.ServerApp'
    echo "🤖 Guess JupyterHub is running..."
    echo "\$JUPYTERHUB_CLIENT_ID = $JUPYTERHUB_CLIENT_ID"
    echo "before:" "$@"
    echo "after : $(echo "$@" | sed 's|--notebook-dir=/home/jovyan | |')"
    exec $(echo "$@" | sed 's|--notebook-dir=/home/jovyan | |')
else
    # === For local build with repo2docker ===
    # Replaces the back end: NotebookApp --> ServerApp
    echo "🐻 Guess Repo2Docker (w/o JupyterHub) is running..."
    echo "before:" "$@"
    echo "after : $(echo "$@" | sed 's/notebook/lab/' | sed 's/NotebookApp/ServerApp/g') --debug"
    exec $(echo "$@" | sed 's/notebook/lab/' | sed 's/NotebookApp/ServerApp/g') --debug
fi
