#!/bin/bash
export SHELL=/usr/bin/zsh

if [[ "$USER" == "jovyan" ]]; then
    # https://jupyterhub.readthedocs.io/en/stable/reference/config-user-env.html#switching-back-to-the-classic-notebook
    # export JUPYTERHUB_SINGLEUSER_APP='jupyter_server.serverapp.ServerApp'
    export JUPYTERHUB_SINGLEUSER_APP='notebook.notebookapp.NotebookApp'
    echo "launch command:" "$@"
    exec "$@"
else
    # Replaces the back end: NotebookApp --> ServerApp
    # echo "before:" "$@"
    # echo "after : $(echo "$@" | sed 's/notebook/lab/' | sed 's/NotebookApp/ServerApp/g')"
    # exec $(echo "$@" | sed 's/notebook/lab/' | sed 's/NotebookApp/ServerApp/g')
    exec "$@"
fi
